# Generated by Django 6.0.8 on 2026-09-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"]},
        ),
    ]
