# Generated by Django 6.0.8 on 2026-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_borrowing_unique_active_borrowing_per_user_book"),
        ("payments", "0003_alter_payment_session_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("borrowing", "type"),
                name="unique_payment_per_borrowing_and_type",
            ),
        ),
    ]
