# Generated by Django 6.0.8 on 2026-10-01 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_image"),
        ("borrowings", "0002_alter_borrowing_actual_return_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actual_return_date__isnull", True)),
                fields=("user", "book"),
                name="unique_active_borrowing_per_user_book",
            ),
        ),
    ]
